//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Web;
namespace CenterWebMake.Models
{

    [System.ComponentModel.DataAnnotations.MetadataType(typeof(LoginMetaData))]
    public partial class Login
    {
        public class LoginMetaData
        {
            [required]
            [DisplayName("账户名")]
            public string UserName { get; set; }
            [required]
            [DisplayName("密码")]
            public string password { get; set; }
            [DisplayName("创建者")]
            public string Creater { get; set; }

        }
       
    }
}
